---
title: "Final paper R code"
author: "Eugene Jang, Eugene Lee"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r load-pkg, message = FALSE}
library(here)  # makes reading data more consistent
library(tidyverse)  # for data manipulation and plotting
library(haven)  # for importing SPSS/SAS/Stata data
library(lme4)  # for multilevel analysis
library(glmmTMB)  # for frequentist longitudinal MLM
#install.packages('TMB', type = 'source')
library(brms)  # for Bayesian longitudinal MLM
library(sjPlot)  # for plotting
library(modelsummary)  # for making tables
library(broom.mixed)  # for obtaining residuals
library(lmerTest)  # for testing in small samples
library(brms)
library(foreign)
library(dplyr)
```

#Import data

```{r import_sav, message=FALSE}
ymsm_dat1 <- read_dta("N2 1.1 - STATA - cleaned and merged with screener data 2020-03-12.dta")
ymsm_dat1

ymsm_dat2 <- read_sav("N2 1.2 - cycle 1 session 2 data  - ALL cases - 2020-01-14.sav")
ymsm_dat2

ymsm_dat1$CaseID <- as.numeric(ymsm_dat1$CaseID)
ymsm_dat2$CaseID <- as.numeric(ymsm_dat2$CaseID)

```



```{r Recode variables}
######################## Condomless sex (Q153 & Q159 - 0 = Never use condoms for both vaginal and anal sex / 1 = Use condoms for either one type of sex) ######################## 

# Change to numeric values
ymsm_dat2$A6_Q153 <- as.numeric(ymsm_dat2$A6_Q153)
ymsm_dat2$A6_Q159 <- as.numeric(ymsm_dat2$A6_Q159)

ymsm_dat2$A7_Q153 <- as.numeric(ymsm_dat2$A7_Q153)
ymsm_dat2$A7_Q159 <- as.numeric(ymsm_dat2$A7_Q159)

ymsm_dat2$A8_Q153 <- as.numeric(ymsm_dat2$A8_Q153)
ymsm_dat2$A8_Q159 <- as.numeric(ymsm_dat2$A8_Q159)

ymsm_dat2$A9_Q153 <- as.numeric(ymsm_dat2$A9_Q153)
ymsm_dat2$A9_Q159 <- as.numeric(ymsm_dat2$A9_Q159)

ymsm_dat2$A10_Q153 <- as.numeric(ymsm_dat2$A10_Q153)
ymsm_dat2$A10_Q159 <- as.numeric(ymsm_dat2$A10_Q159)

ymsm_dat2$A6_Q132 <- as.numeric(ymsm_dat2$A6_Q132)
ymsm_dat2$A7_Q132 <- as.numeric(ymsm_dat2$A7_Q132)
ymsm_dat2$A8_Q132 <- as.numeric(ymsm_dat2$A8_Q132)
ymsm_dat2$A9_Q132 <- as.numeric(ymsm_dat2$A9_Q132)
ymsm_dat2$A10_Q132 <- as.numeric(ymsm_dat2$A10_Q132)

ymsm_dat2$A6_Q146 <- as.numeric(ymsm_dat2$A6_Q146)
ymsm_dat2$A7_Q146 <- as.numeric(ymsm_dat2$A7_Q146)
ymsm_dat2$A8_Q146 <- as.numeric(ymsm_dat2$A8_Q146)
ymsm_dat2$A9_Q146 <- as.numeric(ymsm_dat2$A9_Q146)
ymsm_dat2$A10_Q146 <- as.numeric(ymsm_dat2$A10_Q146)

ymsm_dat2$A6_Q147 <- as.numeric(ymsm_dat2$A6_Q147)
ymsm_dat2$A6_Q148 <- as.numeric(ymsm_dat2$A6_Q148)

ymsm_dat2$A7_Q147 <- as.numeric(ymsm_dat2$A7_Q147)
ymsm_dat2$A7_Q148 <- as.numeric(ymsm_dat2$A7_Q148)

ymsm_dat2$A8_Q147 <- as.numeric(ymsm_dat2$A8_Q147)
ymsm_dat2$A8_Q148 <- as.numeric(ymsm_dat2$A8_Q148)

ymsm_dat2$A9_Q147 <- as.numeric(ymsm_dat2$A9_Q147)
ymsm_dat2$A9_Q148 <- as.numeric(ymsm_dat2$A9_Q148)

ymsm_dat2$A10_Q147 <- as.numeric(ymsm_dat2$A10_Q147)
ymsm_dat2$A10_Q148 <- as.numeric(ymsm_dat2$A10_Q148)


ymsm_dat2$A6_Qcondomuse <- ifelse(ymsm_dat2$A6_Q153 == '5' | ymsm_dat2$A6_Q159 == '5', '0',
                                   ifelse(ymsm_dat2$A6_Q153 == '-2' & ymsm_dat2$A6_Q159 == '-2', 'NA',
                                          '1'))
ymsm_dat2$A7_Qcondomuse <- ifelse(ymsm_dat2$A7_Q153 == '5' | ymsm_dat2$A7_Q159 == '5', '0',
                                   ifelse(ymsm_dat2$A7_Q153 == '-2' & ymsm_dat2$A7_Q159 == '-2', 'NA',
                                          '1'))
ymsm_dat2$A8_Qcondomuse <- ifelse(ymsm_dat2$A8_Q153 == '5' | ymsm_dat2$A8_Q159 == '5', '0',
                                   ifelse(ymsm_dat2$A8_Q153 == '-2' & ymsm_dat2$A8_Q159 == '-2', 'NA',
                                          '1'))
ymsm_dat2$A9_Qcondomuse <- ifelse(ymsm_dat2$A9_Q153 == '5' | ymsm_dat2$A9_Q159 == '5', '0',
                                   ifelse(ymsm_dat2$A9_Q153 == '-2' & ymsm_dat2$A9_Q159 == '-2', 'NA',
                                          '1'))
ymsm_dat2$A10_Qcondomuse <- ifelse(ymsm_dat2$A10_Q153 == '5' | ymsm_dat2$A10_Q159 == '5', '0',
                                   ifelse(ymsm_dat2$A10_Q153 == '-2' & ymsm_dat2$A10_Q159 == '-2', 'NA',
                                          '1'))


######################## Shared Sex drug use (S2 Q169-categorical variable)  #########################

# Change to numeric values
ymsm_dat2$A6_Q169 <- as.numeric(ymsm_dat2$A6_Q169)
ymsm_dat2$A7_Q169 <- as.numeric(ymsm_dat2$A7_Q169)
ymsm_dat2$A8_Q169 <- as.numeric(ymsm_dat2$A8_Q169)
ymsm_dat2$A9_Q169 <- as.numeric(ymsm_dat2$A9_Q169)
ymsm_dat2$A10_Q169 <- as.numeric(ymsm_dat2$A10_Q169)

# Recode to binary variable (0= don't share sex drug / 1 = share sex drug)
ymsm_dat2$A6_Qsexdrug <- ifelse(ymsm_dat2$A6_Q169 == '35', '0',
                               ifelse(ymsm_dat2$A6_Q169 == '37', 'NA',
                                      '1')) 
ymsm_dat2$A7_Qsexdrug <- ifelse(ymsm_dat2$A7_Q169 == '35', '0',
                               ifelse(ymsm_dat2$A7_Q169 == '37', 'NA',
                                      '1')) 
ymsm_dat2$A8_Qsexdrug <- ifelse(ymsm_dat2$A8_Q169 == '35', '0',
                               ifelse(ymsm_dat2$A8_Q169 == '37', 'NA',
                                      '1')) 
ymsm_dat2$A9_Qsexdrug <- ifelse(ymsm_dat2$A9_Q169 == '35', '0',
                               ifelse(ymsm_dat2$A9_Q169 == '37', 'NA',
                                      '1')) 
ymsm_dat2$A10_Qsexdrug <- ifelse(ymsm_dat2$A10_Q169 == '35', '0',
                               ifelse(ymsm_dat2$A10_Q169 == '37', 'NA',
                                      '1')) 

######################## Casual sex partner (S2 Q132 - dummy variable; 1=casual or exchange partners, 0 = main partner)  #########################

ymsm_dat2$A6_Qcasualptnr <- ifelse(ymsm_dat2$A6_Q132 == '1', '0',
                                   ifelse(ymsm_dat2$A6_Q132 == '-2' | ymsm_dat2$A6_Q132 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A7_Qcasualptnr <- ifelse(ymsm_dat2$A7_Q132 == '1', '0',
                                   ifelse(ymsm_dat2$A7_Q132 == '-2' | ymsm_dat2$A7_Q132 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A8_Qcasualptnr <- ifelse(ymsm_dat2$A8_Q132 == '1', '0',
                                   ifelse(ymsm_dat2$A8_Q132 == '-2' | ymsm_dat2$A8_Q132 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A9_Qcasualptnr <- ifelse(ymsm_dat2$A9_Q132 == '1', '0',
                                   ifelse(ymsm_dat2$A9_Q132 == '-2' | ymsm_dat2$A9_Q132 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A10_Qcasualptnr <- ifelse(ymsm_dat2$A10_Q132 == '1', '0',
                                   ifelse(ymsm_dat2$A10_Q132 == '-2' | ymsm_dat2$A10_Q132 == '-1', 'NA',
                                          '1'))

######################## HIV status (S2 Q146 - positive = 1, negative = 0)  #########################

ymsm_dat2$A6_Qalter_hiv <- ifelse(ymsm_dat2$A6_Q146 == '2', '0',
                                   ifelse(ymsm_dat2$A6_Q146 == '-2' | ymsm_dat2$A6_Q146 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A7_Qalter_hiv <- ifelse(ymsm_dat2$A7_Q146 == '2', '0',
                                   ifelse(ymsm_dat2$A7_Q146 == '-2' | ymsm_dat2$A7_Q146 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A8_Qalter_hiv <- ifelse(ymsm_dat2$A8_Q146 == '2', '0',
                                   ifelse(ymsm_dat2$A8_Q146 == '-2' | ymsm_dat2$A8_Q146 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A9_Qalter_hiv <- ifelse(ymsm_dat2$A9_Q146 == '2', '0',
                                   ifelse(ymsm_dat2$A9_Q146 == '-2' | ymsm_dat2$A9_Q146 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A10_Qalter_hiv <- ifelse(ymsm_dat2$A10_Q146 == '2', '0',
                                   ifelse(ymsm_dat2$A10_Q146 == '-2' | ymsm_dat2$A10_Q146 == '-1', 'NA',
                                          '1'))


######################## HIV status disclosure (S2 Q147, Q148 - disclosed before sex = 1, all others = 0)  #########################

# Discuss alter's HIV status (Q147)
ymsm_dat2$A6_Qhiv_disclose_alter <- ifelse(ymsm_dat2$A6_Q147 == '2' | ymsm_dat2$A6_Q147 == '3', '0',
                                   ifelse(ymsm_dat2$A6_Q147 == '-2' | ymsm_dat2$A6_Q147 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A7_Qhiv_disclose_alter <- ifelse(ymsm_dat2$A7_Q147 == '2' | ymsm_dat2$A7_Q147 == '3', '0',
                                   ifelse(ymsm_dat2$A7_Q147 == '-2' | ymsm_dat2$A7_Q147 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A8_Qhiv_disclose_alter <- ifelse(ymsm_dat2$A8_Q147 == '2' | ymsm_dat2$A8_Q147 == '3', '0',
                                   ifelse(ymsm_dat2$A8_Q147 == '-2' | ymsm_dat2$A8_Q147 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A9_Qhiv_disclose_alter <- ifelse(ymsm_dat2$A9_Q147 == '2' | ymsm_dat2$A9_Q147 == '3', '0',
                                   ifelse(ymsm_dat2$A9_Q147 == '-2' | ymsm_dat2$A9_Q147 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A10_Qhiv_disclose_alter <- ifelse(ymsm_dat2$A10_Q147 == '2' | ymsm_dat2$A10_Q147 == '3', '0',
                                   ifelse(ymsm_dat2$A10_Q147 == '-2' | ymsm_dat2$A10_Q147 == '-1', 'NA',
                                          '1'))

# Discuss ego's HIV status (Q148)
ymsm_dat2$A6_Qhiv_disclose_ego <- ifelse(ymsm_dat2$A6_Q148 == '2' | ymsm_dat2$A6_Q148 == '3', '0',
                                   ifelse(ymsm_dat2$A6_Q148 == '-2' | ymsm_dat2$A6_Q148 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A7_Qhiv_disclose_ego <- ifelse(ymsm_dat2$A7_Q148 == '2' | ymsm_dat2$A7_Q148 == '3', '0',
                                   ifelse(ymsm_dat2$A7_Q148 == '-2' | ymsm_dat2$A7_Q148 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A8_Qhiv_disclose_ego <- ifelse(ymsm_dat2$A8_Q148 == '2' | ymsm_dat2$A8_Q148 == '3', '0',
                                   ifelse(ymsm_dat2$A8_Q148 == '-2' | ymsm_dat2$A8_Q148 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A9_Qhiv_disclose_ego <- ifelse(ymsm_dat2$A9_Q148 == '2' | ymsm_dat2$A9_Q148 == '3', '0',
                                   ifelse(ymsm_dat2$A9_Q148 == '-2' | ymsm_dat2$A9_Q148 == '-1', 'NA',
                                          '1'))
ymsm_dat2$A10_Qhiv_disclose_ego <- ifelse(ymsm_dat2$A10_Q148 == '2' | ymsm_dat2$A10_Q148 == '3', '0',
                                   ifelse(ymsm_dat2$A10_Q148 == '-2' | ymsm_dat2$A10_Q148 == '-1', 'NA',
                                          '1'))

# Mutual disclosure of HIV status
ymsm_dat2$A6_Qhiv_disclose_mutual <- ifelse(ymsm_dat2$A6_Qhiv_disclose_alter == '1' & ymsm_dat2$A6_Qhiv_disclose_ego == '1', '1',
                                   ifelse(ymsm_dat2$A6_Qhiv_disclose_alter == 'NA' | ymsm_dat2$A6_Qhiv_disclose_ego == 'NA', 'NA',
                                          '0'))
ymsm_dat2$A7_Qhiv_disclose_mutual <- ifelse(ymsm_dat2$A7_Qhiv_disclose_alter == '1' & ymsm_dat2$A7_Qhiv_disclose_ego == '1', '1',
                                   ifelse(ymsm_dat2$A7_Qhiv_disclose_alter == 'NA' | ymsm_dat2$A7_Qhiv_disclose_ego == 'NA', 'NA',
                                          '0'))
ymsm_dat2$A8_Qhiv_disclose_mutual <- ifelse(ymsm_dat2$A8_Qhiv_disclose_alter == '1' & ymsm_dat2$A8_Qhiv_disclose_ego == '1', '1',
                                   ifelse(ymsm_dat2$A8_Qhiv_disclose_alter == 'NA' | ymsm_dat2$A8_Qhiv_disclose_ego == 'NA', 'NA',
                                          '0'))
ymsm_dat2$A9_Qhiv_disclose_mutual <- ifelse(ymsm_dat2$A9_Qhiv_disclose_alter == '1' & ymsm_dat2$A9_Qhiv_disclose_ego == '1', '1',
                                   ifelse(ymsm_dat2$A9_Qhiv_disclose_alter == 'NA' | ymsm_dat2$A9_Qhiv_disclose_ego == 'NA', 'NA',
                                          '0'))
ymsm_dat2$A10_Qhiv_disclose_mutual <- ifelse(ymsm_dat2$A10_Qhiv_disclose_alter == '1' & ymsm_dat2$A10_Qhiv_disclose_ego == '1', '1',
                                   ifelse(ymsm_dat2$A10_Qhiv_disclose_alter == 'NA' | ymsm_dat2$A10_Qhiv_disclose_ego == 'NA', 'NA',
                                          '0'))

```


```{r Recode lv-2 variables}
######################## Ego's HIV status (S2 Q242 - positive = 1, negative = 0)  #########################
ymsm_dat1$Q242 <- as.numeric(ymsm_dat1$Q242)
ymsm_dat1$Qego_hiv <- ifelse(ymsm_dat1$Q242 == '2', '0',
                                   ifelse(ymsm_dat1$Q242 == '1', '1',
                                          'NA'))


######################## Ego's depression (S2 Q25-34 / Q28, Q31 reverse coding)  #########################

ymsm_dat1$Q25 <- as.numeric(ymsm_dat1$Q25)
ymsm_dat1$Q26 <- as.numeric(ymsm_dat1$Q26)
ymsm_dat1$Q27 <- as.numeric(ymsm_dat1$Q27)
ymsm_dat1$Q28 <- as.numeric(ymsm_dat1$Q28)
ymsm_dat1$Q29 <- as.numeric(ymsm_dat1$Q29)
ymsm_dat1$Q30 <- as.numeric(ymsm_dat1$Q30)
ymsm_dat1$Q31 <- as.numeric(ymsm_dat1$Q31)
ymsm_dat1$Q32 <- as.numeric(ymsm_dat1$Q32)
ymsm_dat1$Q33 <- as.numeric(ymsm_dat1$Q33)
ymsm_dat1$Q34 <- as.numeric(ymsm_dat1$Q34)

ymsm_dat1 <- ymsm_dat1 %>%
  mutate(Q28 = case_when(Q28 == '1' ~ '4',
                            Q28 == '2' ~ '3',
                            Q28 == '3' ~ '2',
                            Q28 == '4' ~ '1',
                            Q28 == '-4' ~ 'NA',
                            Q28 == '-3' ~ 'NA'))

ymsm_dat1 <- ymsm_dat1 %>%
  mutate(Q31 = case_when(Q31 == '1' ~ '4',
                            Q31 == '2' ~ '3',
                            Q31 == '3' ~ '2',
                            Q31 == '4' ~ '1',
                            Q31 == '-4' ~ 'NA',
                            Q31 == '-3' ~ 'NA'))

ymsm_dat1$Q25 <- as.numeric(ymsm_dat1$Q25)
ymsm_dat1$Q26 <- as.numeric(ymsm_dat1$Q26)
ymsm_dat1$Q27 <- as.numeric(ymsm_dat1$Q27)
ymsm_dat1$Q28 <- as.numeric(ymsm_dat1$Q28)
ymsm_dat1$Q29 <- as.numeric(ymsm_dat1$Q29)
ymsm_dat1$Q30 <- as.numeric(ymsm_dat1$Q30)
ymsm_dat1$Q31 <- as.numeric(ymsm_dat1$Q31)
ymsm_dat1$Q32 <- as.numeric(ymsm_dat1$Q32)
ymsm_dat1$Q33 <- as.numeric(ymsm_dat1$Q33)
ymsm_dat1$Q34 <- as.numeric(ymsm_dat1$Q34)

ymsm_dat1$Qdepression <- rowMeans(select(ymsm_dat1, 38:47), na.rm = FALSE)

```



```{r merge datasets}
dat_join <- inner_join(ymsm_dat1, ymsm_dat2, by="CaseID")
```


```{r}
ymsm_sub <- subset(dat_join, select = c('CaseID', 'ResponseId.x', 'A6_Qcondomuse','A7_Qcondomuse','A8_Qcondomuse','A9_Qcondomuse','A10_Qcondomuse',  'A6_Qsexdrug', 'A7_Qsexdrug', 'A8_Qsexdrug', 'A9_Qsexdrug', 'A10_Qsexdrug', 'A6_Qcasualptnr', 'A7_Qcasualptnr', 'A8_Qcasualptnr', 'A9_Qcasualptnr', 'A10_Qcasualptnr', 'A6_Qalter_hiv', 'A7_Qalter_hiv', 'A8_Qalter_hiv', 'A9_Qalter_hiv', 'A10_Qalter_hiv', 'A6_Qhiv_disclose_alter', 'A7_Qhiv_disclose_alter', 'A8_Qhiv_disclose_alter', 'A9_Qhiv_disclose_alter', 'A10_Qhiv_disclose_alter', 'A6_Qhiv_disclose_ego', 'A7_Qhiv_disclose_ego', 'A8_Qhiv_disclose_ego', 'A9_Qhiv_disclose_ego', 'A10_Qhiv_disclose_ego', 'A6_Qhiv_disclose_mutual', 'A7_Qhiv_disclose_mutual', 'A8_Qhiv_disclose_mutual', 'A9_Qhiv_disclose_mutual', 'A10_Qhiv_disclose_mutual', 'Q227.x', 'Qdepression', 'Qego_hiv', 'Q67_1', 'Q67_2', 'Q67_3', 'Q67_4', 'Q67_5'))
```



## Wide and Long Format

```{r long-to-wide}
final_dat <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qsexdrug:A10_Qsexdrug,  # specify the columns of repeated measures
        names_to = "Alter", # name of the new column to create to indicate item id
        names_prefix = "A", # remove "rt_sec" from the item ID column
        values_to = "Response_sexdrug", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat2 <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qcondomuse:A10_Qcondomuse,  # specify the columns of repeated measures
        names_to = "condomuse", # name of the new column to create to indicate item id
        names_prefix = "A", # remove "rt_sec" from the item ID column
        values_to = "Response_condomuse", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat4 <- ymsm_sub %>%
    pivot_longer(
        cols = Q67_1:Q67_5,  # specify the columns of repeated measures
        names_to = "alter_list", # name of the new column to create to indicate item id
        names_prefix = "Q", # remove "rt_sec" from the item ID column
        values_to = "Existing_Alters", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat5 <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qcasualptnr:A10_Qcasualptnr,  # specify the columns of repeated measures
        names_to = "casualptnr", # name of the new column to create to indicate item id
        names_prefix = "Q", # remove "rt_sec" from the item ID column
        values_to = "Response_casualptnr", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat6 <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qalter_hiv:A10_Qalter_hiv,  # specify the columns of repeated measures
        names_to = "alter_hiv", # name of the new column to create to indicate item id
        names_prefix = "Q", # remove "rt_sec" from the item ID column
        values_to = "Response_alter_hiv", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat7 <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qhiv_disclose_alter:A10_Qhiv_disclose_alter,  # specify the columns of repeated measures
        names_to = "hiv_disclose_alter", # name of the new column to create to indicate item id
        names_prefix = "Q", # remove "rt_sec" from the item ID column
        values_to = "Response_hiv_disclose_alter", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat8 <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qhiv_disclose_ego:A10_Qhiv_disclose_ego,  # specify the columns of repeated measures
        names_to = "hiv_disclose_ego", # name of the new column to create to indicate item id
        names_prefix = "Q", # remove "rt_sec" from the item ID column
        values_to = "Response_hiv_disclose_ego", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat9 <- ymsm_sub %>%
    pivot_longer(
        cols = A6_Qhiv_disclose_mutual:A10_Qhiv_disclose_mutual,  # specify the columns of repeated measures
        names_to = "hiv_disclose_mutual", # name of the new column to create to indicate item id
        names_prefix = "Q", # remove "rt_sec" from the item ID column
        values_to = "Response_hiv_disclose_mutual", # name of new column containing the response
    ) %>%
    rmarkdown::paged_table()

final_dat$Response_condomuse <- final_dat2$Response_condomuse
final_dat$Existing_Alters <- final_dat4$Existing_Alters
final_dat$Response_casualptnr <- final_dat5$Response_casualptnr
final_dat$Response_alter_hiv <- final_dat6$Response_alter_hiv
final_dat$Response_hiv_disclose_alter <- final_dat7$Response_hiv_disclose_alter
final_dat$Response_hiv_disclose_ego <- final_dat8$Response_hiv_disclose_ego
final_dat$Response_hiv_disclose_mutual <- final_dat9$Response_hiv_disclose_mutual
final_dat$Alter <- gsub("_Qsexdrug","",as.character(final_dat$Alter))


########### Adding ego-level (lv-2) variables ###########
final_dat10 <- subset(final_dat, select = c('CaseID', 'ResponseId.x', 'Q227.x', 'Qdepression', 'Qego_hiv', 'Alter', 'Response_condomuse','Response_sexdrug', 'Existing_Alters', 'Response_casualptnr', 'Response_alter_hiv', 'Response_hiv_disclose_alter', 'Response_hiv_disclose_ego', 'Response_hiv_disclose_mutual'))

# Ego's habitual sex drug use (S1 Q227.x)
final_dat10$habitualsexdrug <- final_dat10$Q227.x
final_dat10$habitualsexdrug <- na_if(final_dat10$habitualsexdrug, -4)

```


```{r}
# Delete all missing alters
final_dat11 <- final_dat10
final_dat11$Existing_Alters <- gsub("SEX ALTER ","",as.character(final_dat11$Existing_Alters))
final_dat11$Existing_Alters <- as.numeric(final_dat11$Existing_Alters)
# final_dat6$Existing_Alters <- final_dat6$Existing_Alters %>% mutate_all(na_if,"")

dt.final_dat11 = data.frame(final_dat11)
final_dat11 <- dt.final_dat11[complete.cases(dt.final_dat11[,c("Existing_Alters")]),]
```

## Model Equation

Lv-1:

$$
  \begin{aligned}
    \text{sexdruguse}_{ij} & \sim \text{Bernoulli}(\mu_{ij}) \\
    \eta_{ij} & = \text{logit}(\mu_{ij}) \\
    \eta_{ij} & = \beta_{0j} + \beta_{1j} \text{condomuse}_{ij} + \beta_{2j} \text{casualptnr}_{ij} + \beta_{2j} \text{alter_hiv}_{ij} + \beta_{4j} \text{hiv_disclose_mutual}_{ij}
  \end{aligned}
$$ 


Lv-2:

$$
\begin{aligned}
  \beta_{0j} & = \gamma_{00} + \gamma_{01} \text{ego_habitual_sex_drug_use_cm}_j + \gamma_{02} \text{mean ego_depression_cm}_j + \gamma_{03} \text{mean ego_hiv_status_cm}_j + u_{0j}   \\
  \beta_{1j} & = \gamma_{10} + u_{1j}  \\
  \beta_{2j} & = \gamma_{20} + u_{2j}  \\
  \beta_{3j} & = \gamma_{30} + u_{3j}  \\
  \beta_{4j} & = \gamma_{40} + u_{4j}  \\
\end{aligned}
$$ 


```{r}
# Change variable type to numeric
final_dat11$Response_condomuse <- as.numeric(final_dat11$Response_condomuse)
final_dat11$Response_sexdrug <- as.numeric(final_dat11$Response_sexdrug)
final_dat11$habitualsexdrug <- as.numeric(final_dat11$habitualsexdrug)
final_dat11$Response_casualptnr <- as.numeric(final_dat11$Response_casualptnr)
final_dat11$Response_alter_hiv <- as.numeric(final_dat11$Response_alter_hiv)
final_dat11$Response_hiv_disclose_alter <- as.numeric(final_dat11$Response_hiv_disclose_alter)
final_dat11$Response_hiv_disclose_ego <- as.numeric(final_dat11$Response_hiv_disclose_ego)
final_dat11$Response_hiv_disclose_mutual <- as.numeric(final_dat11$Response_hiv_disclose_mutual)
final_dat11$Qdepression <- as.numeric(final_dat11$Qdepression)
final_dat11$Qego_hiv <- as.numeric(final_dat11$Qego_hiv)
```

```{r}
#cluster mean centering
final_dat11 <- final_dat11 %>%
  group_by(CaseID) %>%
  mutate(Response_condomuse_cm = mean(Response_condomuse, na.rm = TRUE),
         Response_condomuse_cmc = Response_condomuse - Response_condomuse_cm,
) %>%
  ungroup()

final_dat11 <- final_dat11 %>%
  group_by(CaseID) %>%
  mutate(Response_casualptnr_cm = mean(Response_casualptnr, na.rm = TRUE),
         Response_casualptnr_cmc = Response_casualptnr - Response_casualptnr_cm,
) %>%
  ungroup()

final_dat11 <- final_dat11 %>%
  group_by(CaseID) %>%
  mutate(Response_alter_hiv_cm = mean(Response_alter_hiv, na.rm = TRUE),
         Response_alter_hiv_cmc = Response_alter_hiv - Response_alter_hiv_cm,
) %>%
  ungroup()

final_dat11 <- final_dat11 %>%
  group_by(CaseID) %>%
  mutate(Response_hiv_disclose_mutual_cm = mean(Response_hiv_disclose_mutual, na.rm = TRUE),
         Response_hiv_disclose_mutual_cmc = Response_hiv_disclose_mutual - Response_hiv_disclose_mutual_cm,
) %>%
  ungroup()

final_dat11 <- final_dat11 %>%
  group_by(CaseID) %>%
  mutate(Qdepression_cm = mean(Qdepression, na.rm = TRUE),
         Qdepression_cmc = Qdepression - Qdepression_cm,
) %>%
  ungroup()

```


```{r missing data}
pMiss <- function(x){sum(is.na(x))/length(x)*100} #function to find percentage
apply(final_dat11,2,pMiss)
```


```{r descriptives}
# Descriptive statistics for variables
sapply(final_dat11, mean, na.rm=TRUE)
sapply(final_dat11, sd, na.rm=TRUE)
```

```{r ICC}
ran_int <- lmer(Response_sexdrug ~ 1 + (1 | CaseID), data = final_dat11)
# Summarize results
summary(ran_int)
variance_components <- as.data.frame(VarCorr(ran_int))
between_var <- variance_components$vcov[1]
within_var <- ((pi)^2)/3
(icc <- between_var / (between_var + within_var))
```


```{r random slope testing}
# We could not test the random slopes because it gives an error such as: "Error: number of observations (=103) < number of random effects (=315) for term (Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual | CaseID); the random-effects parameters are probably unidentifiable"


# # First, no random slopes
# m0 <- glmer(Response_sexdrug ~ Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual + Qdepression + Qego_hiv + habitualsexdrug + (1 | CaseID),
#     data = final_dat11,
#     family = binomial("logit")
# )
# summary(m0)

# #Test variables one by one
# # Response_condomuse
# m1 <- glmer(Response_sexdrug ~ Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual + Qdepression + Qego_hiv + habitualsexdrug + (Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual | CaseID),
#     data = final_dat11,
#     family = binomial("logit")
# )
# summary(m1)
# anova(m1, m0)
# 

# # Response_casualptnr
# m2 <- glmer(Response_sexdrug ~ Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual + Qdepression + Qego_hiv + habitualsexdrug + (Response_casualptnr | CaseID),
#     data = final_dat11,
#     family = binomial("logit")
# )
# summary(m2)
# anova(m2, m0) 
# 
# # Response_alter_hiv
# m3 <- glmer(Response_sexdrug ~ Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual + Qdepression + Qego_hiv + habitualsexdrug + (Response_alter_hiv | CaseID),
#     data = final_dat11,
#     family = binomial("logit")
# )
# summary(m3)
# anova(m3, m0) 
# 
# # Response_hiv_disclose_mutual
# m4 <- glmer(Response_sexdrug ~ Response_condomuse + Response_casualptnr + Response_alter_hiv + Response_hiv_disclose_mutual + Qdepression + Qego_hiv + habitualsexdrug + (Response_hiv_disclose_mutual | CaseID),
#     data = final_dat11,
#     family = binomial("logit")
# )
# summary(m4)
# anova(m4, m0) 

```

```{r}
# Final model (without random slopes)
m1_logit <- glmer(Response_sexdrug ~ Response_condomuse + Response_condomuse_cm + Response_casualptnr + Response_casualptnr_cm + Response_alter_hiv + Response_alter_hiv_cm + Response_hiv_disclose_mutual + Response_hiv_disclose_mutual_cm + Qdepression + Qego_hiv + habitualsexdrug + (1 | CaseID),
    data = final_dat11,
    family = binomial("logit")
)
summary(m1_logit)
```


```{r}
m_base <- glmer(
    Response_sexdrug ~ 1 + (1 | CaseID),
    data = final_dat11,
    family = binomial("logit")
)


msummary(list(
  "Baseline model" = m_base,
  "Full model" = m1_logit),
         title = "Table 2. Parameter Estimates",
         statistic = c('std.error', 'conf.int'),
         stars = TRUE,
         conf_level = .95)

```

```{r mood graph}
plot_model(m1_logit,
           type = "pred",
           show.data = TRUE,
           title = c('Figure 1'),
           jitter = 0.1)
```


```{r Odds ratio}
# Odds ratio for depression's coefficient
exp(1.2299)
```
